### ISSUE TITLE
ImportError: No module named jtnn

### ISSUE THREAD

**Issue by wanlei452229** [wengong-jin/icml18-jtnn#1]
Traceback (most recent call last):
  File "pretrain.py", line 12, in <module>
    from jtnn import *
ImportError: No module named jtnn

**Comment by wengong-jin** [comment]
Suppose you put your code in $DIR/icml18-jtnn, please run the following code:
`export PYTHONPATH=$DIR/icml18-jtnn/jtnn`

**Comment by xuzhang5788** [comment]
@wengong-jin 
I had the same problem first, then I checked here and export python path to my directory. like this 

export PYTHONPATH=/media/projects/icml18-jtnn/jtnn. 

Then ran pretrain.py again, still got the same error like
Traceback (most recent call last):
  File "pretrain.py", line 12, in <module>
    from jtnn import *
ImportError: No module named 'jtnn'

Then I read your .md file, you asked to do

export PYTHONPATH=/media/projects/icml18-jtnn     (without /jtnn)

reran pretrain.py, I got new error like

Traceback (most recent call last):
  File "pretrain.py", line 12, in <module>
    from jtnn import *
  File "/media/projects/icml18-jtnn/jtnn/__init__.py", line 1, in <module>
    from mol_tree import Vocab, MolTree
ImportError: No module named 'mol_tree'

I think there is a problem on calling modules through the different directories. Any advice? Many thanks.

**Comment by gopick** [comment]
Did you find any solution for it?

**Comment by wengong-jin** [comment]
Hi,

I think the solution is to 
```
export PYTHONPATH=$path_to_repo/icml18-jtnn/
```

Wengong

**Comment by zoey1996** [comment]
I do this like what you said, but the problem still exist.
Traceback (most recent call last):
  File "preprocess.py", line 9, in <module>
    from fast_jtnn import *
  File "/home/zhai/cxh/icml18-jtnn/fast_jtnn/__init__.py", line 1, in <module>
    from mol_tree import Vocab, MolTree
ModuleNotFoundError: No module named 'mol_tree'

**Comment by shadow150519** [comment]
i also have the same problem, and i run the command
`export PYTHONPATH=$project_dir/icml18-jtnn/`
but i still get the error  below
Traceback (most recent call last):
  File "decode.py", line 9, in <module>
    from jtvae import (Vocab,
  File "/home/wangtianxing/GenDA/StructureGeneration/GEN/jtvae/__init__.py", line 1, in <module>
    from .jtnn.mol_tree import Vocab, MolTree
  File "/home/wangtianxing/GenDA/StructureGeneration/GEN/jtvae/jtnn/__init__.py", line 1, in <module>
    from mol_tree import Vocab, MolTree
ModuleNotFoundError: No module named 'mol_tree'
so does anyone have solution?
