### ISSUE TITLE
A problem while I run preprocess.py

### ISSUE THREAD

**Issue by zoey1996** [wengong-jin/icml18-jtnn#52]
when  I  run preprocess.py, I meet a problem.
Traceback (most recent call last):
  File "preprocess.py", line 9, in <module>
    from fast_jtnn import *
  File "/home/zhai/cxh/icml18-jtnn/fast_jtnn/__init__.py", line 1, in <module>
    from mol_tree import Vocab, MolTree
ModuleNotFoundError: No module named 'mol_tree'
But I add export PYTHONPATH=$PREFIX/icml18-jtnn to my environment variables.

**Comment by ShuoTian172** [comment]
I have the same problem...

**Comment by sbanwaskar** [comment]
I have a problem with preprocess.py 
raceback (most recent call last):
  File "preprocess.py", line 10, in <module>
    from fast_jtnn import *
  File "/home/shreya/Desktop/jtnn/icml18-jtnn-master/fast_molvae/fast_jtnn/__init__.py", line 2, in <module>
    from jtnn_vae import JTNNVAE
  File "/home/shreya/Desktop/jtnn/icml18-jtnn-master/fast_molvae/jtnn_vae.py", line 5, in <module>
    from nnutils import create_var, flatten_tensor, avg_pool
ImportError: cannot import name 'flatten_tensor' from 'nnutils'

**Comment by Anshu-Raj-18** [comment]
Hi @sbanwaskar / @ShuoTian172  is this issue still open? 

I'm preparing for GSoC and looking to make some contributions to this repository. I would love to work on it and try fixing this if it's available. Thanks!
