### ISSUE TITLE
GPU memory growth

### ISSUE THREAD

**Issue by kirtov** [wengong-jin/icml18-jtnn#9]
I run 
```
CUDA_VISIBLE_DEVICES=3 python pretrain.py --train ../train.txt --vocab ../jtnn/vocab.txt --hidden 450 --depth 3 --latent 56 --batch 32 --save_dir pre_model/
```
But after ~10-20 iterations script fails with
```
Traceback (most recent call last):
  File "pretrain.py", line 108, in <module>
    loss.backward()
  File "/home/kkochetov/nfp_conda/lib/python2.7/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/kkochetov/nfp_conda/lib/python2.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generic/THCStorage.cu:58
```

I tried gc.collect() and torch.cuda.empty_cache(), but there is an another strange problem. After each batch gpu memory was freed to minimum, but when model.forward() was called after that more and more memory allocated from gpu. More and more until at some moment model allocates more memory, than GPU have (>12Gb).

What the problem? Can anyone help?

**Comment by Oktai15** [comment]
@kirtov you can follow at #10

**Comment by kirtov** [comment]
@wengong-jin I found, that big memory growth refers to big MolTrees objects. There is no big complex molecules in ZINC dataset, so there is no problem too. But If I pass big molecule, MolTree object will be very big and It cause GPU memory issues. Can you help me, where I can find tensors/variables related to this problem? Maybe I can optimize it somehow without just dropping big molecules?

**Comment by wengong-jin** [comment]
Hi,
You can try three things:
1. reduce batch size
2. reduce hidden size from 450 -> 300, for instance.
2. In chemutils.py, change `MAX_NCAND` to smaller value.
Please also check the size of list `node.cands` of a `MolTreeNode` object `node`. For big molecules, the size might be large.

**Comment by abhik1368** [comment]
What is the ideal settings for running jtnn with molecular weight ranging from 200-1000 ?

**Comment by faizangiki** [comment]
> 

Have been you JTVAE-trained for compounds with molecular weights ranging from 200 to 1000? If so, please share the network configuration. I am extremely grateful to you.
